# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20151220_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', jsonfield.fields.JSONField(blank=True, default='{}', null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.Graph')),
            ],
        ),
    ]
