# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_infection'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
